TYPE %wmpath%\INST\HOLDEATH.RFS>>%wmpath%\TEMP\RESRFF.RFS
TYPE %wmpath%\INST\HOLDSND.RFS>>%wmpath%\TEMP\SNDRFF.RFS
TYPE %wmpath%\PTCH\HOLYD.CRK>>%wmpath%\TEMP\CRKEXE.CRK
ECHO F>>%wmpath%\TEMP\LTRS.FLG